version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trivia-app1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12ru8g8oiohxo"
s3_prefix = "trivia-app1"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
